app = "music-release-artists-api"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3333"
  HOST = "0.0.0.0"
  LOG_LEVEL = "info"
  TZ = "Europe/Rome"
  DB_CONNECTION = "pg"
  SESSION_DRIVER = "cookie"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  release_command = "node build/ace migration:run --force"

[processes]
  app = "node build/bin/server.js"
