/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArtistSchema extends BaseModel {
  static $columns = ['createdAt', 'followers', 'genres', 'id', 'imageUrl', 'lastSyncedAt', 'name', 'spotifyArtistId', 'updatedAt'] as const
  $columns = ArtistSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare followers: number | null
  @column()
  declare genres: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare spotifyArtistId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationLogSchema extends BaseModel {
  static $columns = ['createdAt', 'errorMessage', 'id', 'releasesCount', 'sentAt', 'status', 'updatedAt', 'userId'] as const
  $columns = NotificationLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare releasesCount: number
  @column.dateTime()
  declare sentAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserArtistSchema extends BaseModel {
  static $columns = ['artistId', 'followedAt', 'id', 'userId'] as const
  $columns = UserArtistSchema.$columns
  @column()
  declare artistId: number
  @column.dateTime()
  declare followedAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['accessTokenEnc', 'avatarUrl', 'country', 'createdAt', 'displayName', 'email', 'emailSentAt', 'emailVerificationToken', 'emailVerifiedAt', 'fullName', 'id', 'notificationEmail', 'notificationFrequency', 'notificationTypes', 'notificationsEnabled', 'password', 'passwordResetSentAt', 'passwordResetToken', 'refreshTokenEnc', 'spotifyId', 'tokenExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accessTokenEnc: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailSentAt: DateTime | null
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notificationEmail: string | null
  @column()
  declare notificationFrequency: string | null
  @column()
  declare notificationTypes: string | null
  @column()
  declare notificationsEnabled: boolean | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordResetSentAt: DateTime | null
  @column()
  declare passwordResetToken: string | null
  @column()
  declare refreshTokenEnc: string | null
  @column()
  declare spotifyId: string | null
  @column.dateTime()
  declare tokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
